### PR TITLE
added line to account for non-cuda devices

### PR DESCRIPTION
**Pull request by toujames**
Modifying this line accounts for non cuda devices or training on cpu-only devices.

### CODE REVIEW

**Comment by jbohnslav** [comment]
Thanks for your contribution. I'm a bit loathe to merge this, because training models will be so slow on CPU that this is a way to enforce that people have access to a GPU. Have you tried training with these changes? How long does it take?

**Comment by toujames** [comment]
Thank You for looking into this.

This code only *fixes* the issue if a user were to *not* have a CUDA device.
This can be handy since some HPC clusters (like ours currently at LIBR) may not have CUDA GPU installed yet.

I've trained it on an example set and it takes about a couple days to train.

**Comment by jbohnslav** [comment]
Merged. Talk to your sys admins about getting some GPUs! There might be some more places where this needs to be changed, e.g. in prediction, but looks good for now.

**Comment by toujames** [comment]
Thank you for the pull. 👍 

Our sys admins do have the GPU's in hand, but installation process seems to be taking a while.

**Pull request merged**
